# Generated by Django 5.2.7 on 2025-10-07 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='manager_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workposition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workposition',
            name='workplace_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workplaces.workplace'),
            preserve_default=False,
        ),
    ]
