# Generated by Django 5.2.7 on 2025-10-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housingassignment',
            old_name='room',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='housingassignment',
            old_name='worker',
            new_name='worker_id',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='accommodation',
            new_name='accommodation_id',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('accommodation_id', 'name')},
        ),
    ]
