# Generated by Django 5.2.7 on 2025-10-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_accommodation_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='manager',
            new_name='manager_id',
        ),
    ]
