# Generated by Django 5.2.7 on 2025-10-07 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_rename_manager_accommodation_manager_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='manager_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managed_accommodations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
